import csv

f = open("control_hier_bench_csv.v", "w")
f.write("// This file was autogenerated by a sweet script!")

with open('controlLogic.csv', mode='r', encoding='utf-8-sig') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            line_count += 1
        f.write(f'\n{row["Syntax"]}: {row["OpCode"]}')
        line_count += 1
    print(f'Processed {line_count} lines.')
