import csv

f = open("control_hier_bench_csv.v", "w")
# Write the head of the file
f.write("""
/*
   CS/ECE 552, Spring '19
   Auto generated by python
*/
module control_hier_bench_csv(/*AUTOARG*/);
   /*AUTOWIRE*/
   // Beginning of automatic wires (for undeclared instantiated-module outputs)
   wire       err;
   wire       RegWrite, DMemWrite,              // From top of control_hier.v
              DMemEn, ALUSrc2, PCSrc,           // From top of control_hier.v
              PCImm, MemToReg, DMemDump, Jump;         // From top of control_hier.v
   wire [1:0] RegDst;                           // From top of control_hier.v
   wire [2:0] SESel;                            // From top of control_hier.v
   // End of automatics
   /*AUTOREGINPUT*/
   // Beginning of automatic reg inputs (for undeclared instantiated-module inputs)
   reg [4:0]  OpCode;                           // To top of control_hier.v
   reg [1:0]  Funct;                            // To top of control_hier.v
   // End of automatics

   integer    cycle_count;

   wire       clk;
   wire       rst;

   reg        fail;
   reg [5:0]  errorCount;

   // Instantiate the module we want to verify

   control_hier DUT(/*AUTOINST*/
                    // Outputs
                    .err                          (err),
                    .RegDst                       (RegDst),
                    .SESel                        (SESel),
                    .RegWrite                     (RegWrite),
                    .DMemWrite                    (DMemWrite),
                    .DMemEn                       (DMemEn),
                    .ALUSrc2                      (ALUSrc2),
                    .PCSrc                        (PCSrc),
                    .PCImm                        (PCImm),
                    .MemToReg                     (MemToReg),
                    .DMemDump                     (DMemDump),
                    .Jump                         (Jump),
                    // Inputs
                    .OpCode                       (OpCode),
                    .Funct                        (Funct));

    assign               clk = DUT.clk_generator.clk;
    assign               rst = DUT.clk_generator.rst;
    initial begin
      errorCount = 6'b0;
      $display("Running Tests...\\n");


""")
# Write each test case
with open('controlLogic.csv', mode='r', encoding='utf-8-sig') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    line_count = 0
    for row in csv_reader:
        f.write(f"""
      OpCode = 5'b{row['OpCode']};
      Funct = 2'bxx;
      repeat(2) @(posedge clk);
      @(posedge clk)begin
        $display("{row['Syntax']}");
        if(
          err !== 1'b{row['err']} ||
          RegDst !== 2'b{row['RegDst']} ||
          SESel !== 3'b{row['SESel']} ||
          RegWrite !== 1'b{row['RegWrite']} ||
          DMemWrite !== 1'b{row['DMemWrite']} ||
          DMemEn !== 1'b{row['DMemEn']} ||
          ALUSrc2 !== 1'b{row['ALUSrc2']} ||
          PCSrc !== 1'b{row['PCSrc']} ||
          MemToReg !== 1'b{row['MemToReg']} ||
          DMemDump !== 1'b{row['DMemDump']} ||
          Jump !== 1'b{row['Jump']} ||
          PCImm !== 1'b{row['PCImm']}
          ) begin
          errorCount = errorCount + 1;
          $display("\tERROR!");
          $display("\tOUTPUT: Opcode: %b   ->   Error: %b, RegDst: %b, SESel: %b, RegWrite: %b, DMemWrite: %b, DMemEn: %b, ALUSrc2: %b, PCSrc: %b, MemToReg: %b, DMemDump: %b, Jump: %b, PCImm: %b\\n", OpCode, err,
                    RegDst,
                    SESel,
                    RegWrite,
                    DMemWrite,
                    DMemEn,
                    ALUSrc2,
                    PCSrc,
                    MemToReg,
                    DMemDump,
                    Jump,
                    PCImm);
          $display("\tEXPECT: Opcode: %b   ->   Error: %b, RegDst: %b, SESel: %b, RegWrite: %b, DMemWrite: %b, DMemEn: %b, ALUSrc2: %b, PCSrc: %b, MemToReg: %b, DMemDump: %b, Jump: %b, PCImm: %b\\n", OpCode, err,
                    RegDst,
                    SESel,
                    RegWrite,
                    DMemWrite,
                    DMemEn,
                    ALUSrc2,
                    PCSrc,
                    MemToReg,
                    DMemDump,
                    Jump,
                    PCImm);
          end else begin
            $display("\tPASSED [%d]", {line_count + 1});
          end
        end""")
        line_count += 1
# Write end of file
f.write(f"""
      $display("Test Completed");
      $display("Number Of Errors: %d", errorCount);
      $finish;
    end

endmodule // control_hier_bench
""")
